const someDangerousCall: unit -> [`FooError string | `UnknownError unit] unit =
  () => { throw `FooError "lolwtf"; };

const f : unit -> unit = () => {
  try {
    someDangerousCall();
  } catch (fooErr : `FooError string) {
    // A specific error...
  } catch (err) {
    // Default error with sum type `FooError string | `UnknownError unit.
  }
};
